# Generated by Django 6.0.5 on 2026-05-26 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablebooking',
            old_name='username',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tablebooking',
            old_name='mobile_number',
            new_name='phone',
        ),
    ]
