# Generated by Django 6.0.5 on 2026-05-26 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_username_tablebooking_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablebooking',
            old_name='phone',
            new_name='mobile_number',
        ),
        migrations.RenameField(
            model_name='tablebooking',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='tablebooking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tablebooking',
            name='timing',
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='booking_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 5, 26, 11, 34, 43, 518812)),
            preserve_default=False,
        ),
    ]
